name: CI Back-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'sgcmapi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: sgcmapi/
        run: mvn compile test
